# Generated by Django 4.1.3 on 2022-11-23 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=30)),
                ('Reg_No', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('Taluka', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('pincode', models.IntegerField(default='443301')),
                ('stu_image', models.ImageField(upload_to='upload/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Students Information',
                'verbose_name_plural': 'Students Informations',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(choices=[('Python', 'Python Programming'), ('SE', 'Software Engineering'), ('DBMS', 'Database Management System'), ('OS', 'Operating System'), ('TOC', 'Theory of Computation'), ('ABC', 'C')], max_length=19)),
                ('Marks', models.IntegerField()),
                ('Semester', models.CharField(choices=[('Odd', 'Winter'), ('Even', 'Summer')], max_length=10)),
                ('Year', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=20)),
                ('Reg_No', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Registration_Number', to='Academics.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mark Information',
                'verbose_name_plural': 'Mark Informations',
            },
        ),
        migrations.CreateModel(
            name='Feedbackform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Feedback', models.TextField()),
                ('Reg_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.student')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.mark')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Information',
                'verbose_name_plural': 'Feedback Informations',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Standard', models.CharField(max_length=50)),
                ('Branch', models.CharField(max_length=20)),
                ('Year', models.CharField(max_length=20)),
                ('Date_of_admission', models.DateField()),
                ('Semester', models.IntegerField(default='443301')),
                ('Reg_No', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Registration_No', to='Academics.student')),
                ('Student_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_names', to='Academics.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Information',
                'verbose_name_plural': 'Admission Informations',
            },
        ),
    ]
