# Generated by Django 4.1.3 on 2022-11-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='Subject',
            field=models.CharField(choices=[('Python', 'Python Programming'), ('SE', 'Software Engineering'), ('DBMS', 'Database Management System'), ('OS', 'Operating System'), ('TOC', 'Theory of Computation'), ('C', 'C')], max_length=19),
        ),
    ]
