# Generated by Django 4.1.3 on 2022-11-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_alter_mark_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackform',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academics.mark'),
        ),
    ]
