# Generated by Django 4.1.3 on 2022-11-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0004_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance Information', 'verbose_name_plural': 'Attendance Informations'},
        ),
    ]
