# Generated by Django 4.1.3 on 2022-11-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0005_alter_attendance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Roll_NO',
            new_name='Roll_No',
        ),
    ]
