# Generated by Django 4.1.3 on 2022-12-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0009_remove_student_stu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
    ]
